## code to prepare `keywords` dataset goes here
keywords <- c(
  "Bayesian Inference",
  "Chemometrics and Computational Physics",
  "Clinical Trial Design Monitoring and Analysis",
  "Cluster Analysis & Finite Mixture Models",
  "Databases with R",
  "Differential Equations",
  "Distributions",
  "Econometrics",
  "Ecological and Environmental analysis",
  "Design and Analysis of Experiments (DoE)",
  "Extreme Value Analysis",
  "Empirical Finance",
  "Functional Data Analysis",
  "Statistical Genetics",
  "Graphical Models",
  "Graphics and Visualisation",
  "High-Performance Computing",
  "Hydrological Data and Modeling",
  "Machine Learning & Statistical Learning",
  "Medical Image Analysis",
  "Meta-Analysis",
  "Missing Data",
  "Model Deployment",
  "Multivariate Statistics",
  "Natural Language Processing",
  "Numerical Mathematics",
  "Official Statistics & Survey Methodology",
  "Optimization and Mathematical Programming",
  "Pharmacokinetic Analysis",
  "Phylogenetics",
  "Psychometric Models and Methods",
  "Reproducible Research",
  "Robust Statistical Methods",
  "Social Sciences",
  "Spatial Analysis",
  "Spatio-Temporal Analysis",
  "Survival Analysis",
  "Teaching Statistics",
  "Time Series Analysis",
  "Tracking Data",
  "Web Technologies and Services"
)

usethis::use_data(keywords, overwrite = TRUE)
